name: Build Docker Image

on:
    workflow_dispatch:
        inputs:
            path:
                description: "Path to Dockerfile"
                required: true
            tag:
                description: "Tag for the Docker image"
                required: true

jobs:
    build:
        name: Build ghcr.io/mainek00n/vuls-targets:${{ inputs.tag }} by ${{ inputs.path }}
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@v5

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ${{ inputs.path }}
                  push: true
                  tags: ghcr.io/mainek00n/vuls-targets:${{ inputs.tag }}
